-- SUPERSEDED - do not run this file. It set up the old account-wide
-- referral system (profiles.referred_by/referral_clicks: whoever's link a
-- new user signed up through earned 20% of every purchase that user ever
-- made). That system has been removed entirely in favor of a per-product
-- one - see migrations/20260928_product_only_referrals.sql, which drops
-- referred_by/referral_clicks and adds orders.referrer_id/ref_product_slug
-- instead. profiles.referral_code and public.referral_payouts (the manual
-- payout-request table) are unchanged and still apply to the new system.
